name: flutter_clock_helper
description: Helper classes for Flutter Clock contest.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.16.0"
  flip_panel: ^1.0.1
  gradient_text: ^1.0.2
  flare_flutter: ^1.5.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
